---
- name: Make API GET call and print results
  hosts: localhost
  tasks:
    - name: Make API GET request
      uri:
        url: "https://serpapi.com/search.html?engine=google_flights&departure_id=BUD&arrival_id=VIE&gl=us&hl=en&currency=USD&outbound_date=2024-05-08&return_date=2024-05-14&api_key=f993cfbb3db7547d47cfae99621152f1288a15b909a385b7e515ae6e3758ac8f"  # Replace with the URL of the API
        method: GET
        timeout: 30
        return_content: yes
      register: api_response

    - name: Print API response
      debug:
        msg: "{{ api_response.json }}"
